# Generated by Django 3.0.3 on 2020-02-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readed',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
