# Generated by Django 3.0.3 on 2020-03-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dev',
            field=models.CharField(default='False', max_length=30),
        ),
    ]
